---
 - name: copy in backup folder from somewhere.
   sudo: true
   synchronize: src={{backup_source}} dest="{{elasticsearch_repo_dir}}"

 - name: install pip
   sudo: true
   apt: name=python-pip state=present

 - name: install elasticsearch pip
   pip: name=elasticsearch state=present

 - name: set es template  mapping if provided
   shell: curl -sS -XPUT 'http://localhost:9200/_template/{{snapshot_indices}}' --data @{{snapshot_template_files }}
   when: snapshot_template_files is defined


 - name: restore es wiki backups
   es_snapshot_restore: elasticsearch_host=http://127.0.0.1:9200 repository_path="{{elasticsearch_repo_dir}}" repository_name=my_backup snapshot_name="{{snapshot_name}}" snapshot_indices="{{snapshot_indices}}" mode=restore state=present
