---
 - name: copy in backup folder from somewhere.
   sudo: true
   synchronize: src={{backup_source}} dest="{{elasticsearch_repo_dir}}"

 - name: install pip
   sudo: true
   apt: name=python-pip state=present

 - name: install elasticsearch pip
   pip: name=elasticsearch state=present

 - name: set es template  mapping if provided
   shell: curl -sS -XPUT '{{elasticsearch_backup_host}}/_template/{{snapshot_indices}}' --data @{{snapshot_template_files }}
   when: snapshot_template_files is defined


 - name: restore es wiki backups
   es_snapshot_restore: elasticsearch_host={{elasticsearch_backup_host}} repository_path="{{elasticsearch_repo_dir}}" repository_name={{elasticsearch_repo_name }} snapshot_name="{{elasticsearch_snapshot_restore_name}}" snapshot_indices="{{elasticsearch_snapshot_indices | default(omit) }}" mode=restore state=present
