---

- name: java | Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    creates=/usr/lib/jvm/java-8-oracle

- name: java | Update repositories
  apt_repository:
    repo={{ item }}
    state=present
    update_cache=yes
  with_items: elasticsearch_apt_repos

- name: java | Install dependencies
  apt:
    pkg={{elasticsearch_apt_java_package}}
    state=present
