---

- name: java | Accept Oracle license prior JDK installation
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections; echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
    creates=/usr/lib/jvm/java-8-oracle
  when: ansible_distribution == "Ubuntu"

- name: java | Update repositories
  apt_repository:
    repo={{ item }}
    state=present
    update_cache=yes
  with_items: elasticsearch_apt_repos
  when: ansible_distribution == "Ubuntu"

- name: java | Install dependencies
  action: >
    {{ansible_pkg_mgr}}
    name={{elasticsearch_java_package}}
    state=present
